### PR TITLE
Alex relevant height

### PR DESCRIPTION
**Pull request by ghost**
- Make the cards for the Relevant Right Now section the same height
- also remove double padding

https://trello.com/c/RZUKMa9H/69-relevant-right-now-cards-should-be-a-consistent-height

looks kind of awkward - lots of empty space. thoughts? might be okay to just leave it. also tried spacing it out evenly, and centering:

lots of empty space in card

spacing it out evenly

centering

### CODE REVIEW

**Comment by ghost** [comment]
The more I look at it, the less bad the extra space at bottom looks

**Comment by ghost** [comment]
thoughts on increasing the text spacing too?

**Comment by anikarabenhorst** [comment]
> The more I look at it, the less bad the extra space at bottom looks

I think bottom spacing is the best option of the three. Especially since most cards will end up having links I think?

**Comment by ghost** [comment]
Cool yeah I agree! Thanks Anika 😄

**Review by nupur-n — APPROVED** [review]
Agree with Anika, I think that the first option with the bottom spacing is the best. It just helps make it look less awkward than if the cards were different height. 

Also idk what's going on w/ the commits i think this includes the npm format one, but imma just approve.

**Comment by ghost** [comment]
Thanks y'all 😄 

about the weird commits – I branched this off of the reformat branch because i assumed it was going to get merged first. then after it gets merged, I rebase on main, and the commits disappear :)

**Review by snwessel — APPROVED** [review]
I agree, I think it looks best this way 👍

**Pull request merged**
