### PR TITLE
Cindy calendar category

### PR DESCRIPTION
**Pull request by cindy1u0**
Screen Shot 2021-02-14 at 3 41 36 PM

### CODE REVIEW

**Review by ghost — APPROVED** [review]
YEEET 🤩

**Review by nupur-n — APPROVED** [review]
beautyyyyyful

**Comment by liu-caro** [comment]
@cindy1u0 thanks for making this change! Does the workshop category have a color? It looks like it's just black in the screenshot

**Comment by cindy1u0** [comment]
> @cindy1u0 thanks for making this change! Does the workshop category have a color? It looks like it's just black in the screenshot

ya the workshop is actually dark blue according to [this doc](https://docs.google.com/document/d/1MEaqAaFq-DJEsP61D7jjGp9fJAc__GgTpRPu-qaiB9U/edit?usp=sharing)

**Review by snwessel — APPROVED** [review]
Wooo

**Pull request merged**
