### PR TITLE
fix warnings

### PR DESCRIPTION
**Pull request by ghost**
# warnings before:

warnings before

# (lack of) warnings after:

(lack of) warnings after

### CODE REVIEW

**Review by feliciazhang — APPROVED** [review]
omg this pleases me thank you!!

**Review by nupur-n — APPROVED** [review]
thank <3 

also a lil unsure what's going on here with the `npm format` commit but will approve heh

**Review by snwessel — APPROVED** [review]
Yesss ❤️ Thank you this was so needed 😍

**Comment by ghost** [comment]
Thanks everyone! 

about the npm reformat commit – I left a comment here explaining why: https://github.com/HackBeanpot/livesite-2021/pull/41#issuecomment-778706128

**Pull request merged**
